language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.37.0
  - 1.38.0
  - 1.39.0
  - 1.40.0
  - 1.41.0
  - 1.42.0
  - 1.43.0
  - 1.44.0
  - 1.45.0
  - 1.46.0
  - 1.54.0

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true